# Generated by Django 3.0.2 on 2020-01-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.TextField()),
                ('contact', models.IntegerField()),
                ('primary_role', models.TextField()),
                ('additional_role_id', models.IntegerField()),
                ('school_id', models.IntegerField()),
                ('school_name', models.TextField()),
                ('block_name', models.TextField()),
                ('district_name', models.TextField()),
                ('dise_code', models.IntegerField()),
            ],
        ),
    ]
