# Generated by Django 3.0.2 on 2020-01-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabledata',
            old_name='additional_role_id',
            new_name='additional_role',
        ),
    ]
