# Generated by Django 3.0.2 on 2020-01-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20200116_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledata',
            name='additional_role',
            field=models.TextField(),
        ),
    ]
